StartupEvents.registry('item', event => {

    event.create('t1_rocket_plating').displayName('T1火箭外层防护板')
    event.create('welded_rocket_plating').displayName('焊接过的火箭外层防护板')
    event.create('hsse_nose_cone').displayName('HSS-E火箭鼻锥')
    event.create('hsse_fin').displayName('HSS-E火箭尾翼')
    event.create('hsse_engine').displayName('HSS-E火箭引擎')
    event.create('trinavine_tank').displayName('三元态金属火箭油箱')
    event.create('trinavine_nose_cone').displayName('三元态金属火箭鼻锥')
    event.create('trinavine_fin').displayName('三元态金属火箭尾翼')
    event.create('trinavine_engine').displayName('三元态金属火箭引擎')
    event.create('osmiridium_nose_cone').displayName('铱锇合金火箭鼻锥')
    event.create('osmiridium_fin').displayName('铱锇合金火箭尾翼')
    event.create('osmiridium_engine').displayName('铱锇合金火箭引擎')
    event.create('americium_nose_cone').displayName('镅火箭鼻锥')
    event.create('americium_fin').displayName('镅火箭尾翼')
    event.create('americium_engine').displayName('镅火箭引擎')
    event.create('shredded_magebloom').displayName('撕碎的法师之花')
    event.create('washed_magebloom').displayName('洗净的法师之花')
    event.create('embraced_luminite_ingot').displayName('灌注夜光锭')
    event.create('neutronium_lattice').displayName('中子晶格')
    event.create('heavy_neutron_filter').displayName('重型中子过滤器')
    event.create('neutronium_seedling').displayName('中子素幼芽')
    event.create('terraweave_cloth').displayName('泰拉纤维布匹')
    event.create('carbon_ethersteel_lattice').displayName('碳纤维以太钢晶格')
    event.create('resplendent_sylvan_nanolattice').displayName('纳米辉煌森林晶格')
    event.create('wrapped_slate_tier_2').displayName('破碎的空白石板')
    event.create('wrapped_slate_tier_3').displayName('破碎的强化石板')
    event.create('wrapped_slate_tier_4').displayName('破碎的灌注石板')
    event.create('wrapped_slate_tier_5').displayName('破碎的恶魔石板')
    event.create('spooled_terraweave').displayName('绕好的泰拉纤维')
    event.create('apprenticebloodorb_frame').displayName('学徒气血宝珠框架')
    event.create('magicianbloodorb_frame').displayName('法师气血宝珠框架')
    event.create('masterbloodorb_frame').displayName('导师气血宝珠框架')
    event.create('archmagebloodorb_frame').displayName('贤者气血宝珠框架')
    event.create('t2_rocket_plating').displayName('T2火箭外层防护板')
    event.create('welded_rocket_plating_mk2').displayName('焊接过的MK2火箭外层防护板')
    event.create('chromatically_doped_nether_star_boule').glow(true).displayName('异彩掺杂的单晶下界之星')
    //Nano Lithography 
    event.create('mana_deposited_wafer').displayName('魔力掺杂晶圆')
    event.create('nano_cpu_mask').displayName('纳米CPU掩膜')
    event.create('prepared_nano_cpu_wafer').displayName('预处理纳米CPU晶圆')
    //Quantum Lithography
    event.create('thundering_mana_deposited_wafer').displayName('雷鸣魔力掺杂晶圆')
    event.create('quantum_cpu_mask').displayName('量子CPU掩膜')
    event.create('prepared_quantum_cpu_wafer').displayName('预处理量子CPU晶圆')
    event.create('seal_shards').displayName('深园碎片')
    event.create('cosmic_meatballs').displayName('寰宇肉丸')
    event.create('prismatic_lens').displayName('异彩透镜')

    event.create('reinforced_respirator', 'helmet').displayName('强化呼吸器').maxDamage(1024).modifyTier(tier => 'breather')


    //Planet and Orbit Icons
    event.create('undergarden_dim').displayName('深暗之园')
})
